version: '3.9'

services:
  chatwood:
    container_name: chatwood-rails
    image: chatwoot/chatwoot
    env_file:
      - stack.env
    volumes:
      - /data/chatwoot/storage:/app/storage:rw
    ports:
      - 3000:3000
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    hostname: rails
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  sidekiq:
    container_name: chatwood-sidekiq
    image: chatwoot/chatwoot
    hostname: sidekiq
    volumes:
      - /data/chatwoot/storage:/app/storage:rw
    env_file:
      - stack.env
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  db:
    image: postgres
    container_name: chatwoot-db
    hostname: chatwoot-db
    volumes:
      - /data/chatwoot/db:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=chatwoot_production
      - POSTGRES_USER=chatwootuser
      - POSTGRES_PASSWORD=chatwootpass
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "chatwoot_production", "-U", "chatwootuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: on-failure:5
  
  redis:
    container_name: chatwoot-redis
    image: redis
    hostname: chatwoot-redis
    volumes:
      - /data/chatwoot/redis:/data:rw
    environment:
      - TZ=Asia/Kuching
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass redispass
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: 1026:100
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    restart: on-failure:5

# docker compose up -d
# docker exec -it chatwood-rails /bin/ash
# bundle exec rails db:chatwoot_prepare
# docker compose up -d